// Auto-generated by contracts/deploy-all.mjs
export const CONTRACTS = {
  router: '0xfcb07695d59a2ffb7a1ce780ddde079f4b6d818b',
  oracle: '0x2732b049aec5040037133c199c64a4ce690902b5',
  drawdownRetire: '0x67f0864dc2d5984f24777243a1d988f130845fc1',
  feeRouter: '0x1ca9a918e50fa1c09ee78cd97b5b024c19bee13b',
  creditLine: '0xc0c86e2ce06ef85ce3679b4ec5be34a4e80f90a0',
  destocks: '0xd826711de519ae96459557f19c9fa47faf727ed3',
  swapRouter02: '0xCaf681a66D020601342297493863E78C959E5cb2',
  ponsFactory: '0xA5aAb3F0c6EeadF30Ef1D3Eb997108E976351feB',
};

export const WELLS = {
  "TSLA": {
    "name": "Tesla Stonk Well",
    "symbol": "wTSLA",
    "address": "0xea9c6da79d361e90c705ef99451ff9debc8ec3ac",
    "equityToken": "0x322F0929c4625eD5bAd873c95208D54E1c003b2d"
  },
  "NVDA": {
    "name": "NVIDIA Stonk Well",
    "symbol": "wNVDA",
    "address": "0x5ec65628056feca2671f796b287edde2f8764240",
    "equityToken": "0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC"
  },
  "AAPL": {
    "name": "Apple Stonk Well",
    "symbol": "wAAPL",
    "address": "0xc9c358c799960094a7de14b24daaa59f6e3d1dd4",
    "equityToken": "0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9"
  },
  "PLTR": {
    "name": "Palantir Stonk Well",
    "symbol": "wPLTR",
    "address": "0x5eb18fca8d6b0f04a81b60a9e1731e7b74edcf84",
    "equityToken": "0x894E1EC2D74FFE5AEF8Dc8A9e84686acCB964F2A"
  },
  "META": {
    "name": "Meta Stonk Well",
    "symbol": "wMETA",
    "address": "0x29b9c11784631638516056e29aa02173e1494829",
    "equityToken": "0xc0D6457C16Cc70d6790Dd43521C899C87ce02f35"
  },
  "GOOGL": {
    "name": "Alphabet Stonk Well",
    "symbol": "wGOOGL",
    "address": "0x506b4913bb052b1046931e722304a5a81df3bec4",
    "equityToken": "0x2e0847E8910a9732eB3fb1bb4b70a580ADAD4FE3"
  },
  "SPY": {
    "name": "SPDR S&P 500 Stonk Well",
    "symbol": "wSPY",
    "address": "0x65800bfeac09a6b97f7865729bc11a857ea0a0bc",
    "equityToken": "0x117cc2133c37B721F49dE2A7a74833232B3B4C0C"
  }
};

export const CONTRACT_LIST = [
  { key: 'router', label: 'GetStock Router', address: CONTRACTS.router },
  { key: 'destocks', label: 'DeStocks Options', address: CONTRACTS.destocks },
  { key: 'creditLine', label: 'Borrow Desk', address: CONTRACTS.creditLine },
  { key: 'feeRouter', label: '70/30 Fee Flywheel', address: CONTRACTS.feeRouter },
  { key: 'oracle', label: 'Stonk Oracle', address: CONTRACTS.oracle },
  { key: 'drawdownRetire', label: 'Buy & Burn Engine', address: CONTRACTS.drawdownRetire },
];

export const hasTradingContracts = Boolean(CONTRACTS.router || CONTRACTS.destocks);
